Urgent: Remove breaking createJSModules call
React Native v0.47.0 removes the createJSModules call, so this @Override now breaks the build.

```
:react-native-code-push:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/Luke/Projects/ClientPOC/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java:305: error: method does not override or implement a method from a supertype
    @Override
    ^
```

Confirmed this change fixes the build.  See RN Breaking Changes in the v0.47.0 release: https://github.com/facebook/react-native/releases/tag/v0.47.0